#!/bin/bash

if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
	echo "Usage: $0 prj pkg rev"
	exit 1;
fi

if [ -d sources/$3 ]; then
	echo "rev $3 already checked out"
	exit 0
fi
mkdir -p sources
cd sources
osc co -c -r $3 $1 $2 || { rm -rf "$2"; exit 1; }
mv "$2" "$3"
rm -rf .osc
