#!/bin/bash

if [ -z "$1" -o -z "$2" ]; then
	echo "Usage: $0 prj pkg [revstart [revend]]"
	exit 1;
fi

set -e
i=${3:-1}
while true; do
	./co "$1" "$2" $i
	i=$((i+1))
	if [ -n "$4" ]; then
		if [ "$i" -gt "$4" ]; then
			break;
		fi
	fi
done
