#!/bin/bash
set -e
rev="$1"
if [ ! -d git ]; then
	mkdir git
	cd git
	git init
	echo .msg >> .git/info/exclude
	echo .changes >> .git/info/exclude
	echo .mailmap >> .git/info/exclude
	echo .rev >> .git/info/exclude
	if [ -e ../mailmap ]; then
		cat ../mailmap > .mailmap
	fi
else
	cd git
	if [ -e ".rev" ]; then
		read rr < .rev
		if [ "$rev" -le "$rr" ]; then
			echo "$rr already imported";
			exit 1
		fi
	fi
fi
rm -rf -- *
echo "$rev" > .rev
> .msg
for f in ../sources/$rev/*.*; do
	case "$f" in
		*.tar.gz|*.tgz) tar -xzf "$f" ;;
		*.tar.bz2|*.tbz2) tar -xjf "$f" ;;
		*.tar.*) echo "unhandled tar archive $f, please fix script"; exit 1;;
		*.changes)
		if [ -e .changes ]; then
			echo >> .msg
			diff -u .changes "$f" | awk '/^\+\+\+/ {next;}/^\+/ {sub(/^\+/,"",$0); print}' >> .msg
		fi
		cat "$f" > .changes
		;;
		*.spec) ;;
		*.old) ;;
		*) cp "$f" . ;;
	esac
done
git add -A
../.docommit "$rev"
