#!/bin/bash

cleanup()
{
	trap EXIT
	if [ -e .changes.bak ]; then
		mv .changes.bak .changes
	fi
}

trap cleanup EXIT

set -e
rev="$1"
irev="${2:-$1}"
if [ -n "${rev//[0-9]/}" ]; then
	echo "invalid rev $rev"
	exit 1
fi
if [ ! -d git ]; then
	mkdir git
	cd git
	git init
	echo .msg >> .git/info/exclude
	echo .changes >> .git/info/exclude
	echo .mailmap >> .git/info/exclude
	echo .rev >> .git/info/exclude
	if [ -e ../mailmap ]; then
		cat ../mailmap > .mailmap
	fi
else
	cd git
	if [ -e ".rev" ]; then
		read rr < .rev
		if [ "$rev" -le "$rr" ]; then
			echo "$rr already imported";
			exit 0
		fi
	fi
fi
echo "$rev" > .rev
rm -rf -- *
> .msg
for f in ../sources/$irev/*; do
	case "$f" in
		*.tar.gz|*.tgz) tar -xzf "$f" ;;
		*.tar.bz2|*.tbz2) tar -xjf "$f" ;;
		*.tar.*) echo "unhandled tar archive $f, please fix script"; exit 1;;
		*.changes)
		if [ -e .changes ]; then
			cat .changes > .changes.bak
			echo >> .msg
			diff -u .changes "$f" | awk '/^\+\+\+/ {next;}/^\+/ {sub(/^\+/,"",$0); print}' >> .msg
		else
			cat "$f" > .msg
		fi
		cat "$f" > .changes
		;;
		*.spec) ;;
		*.old) ;;
		*/MD5SUMS) ;;
		*/MD5SUMS.meta) ;;
		*/ready) ;;
		*) cp "$f" . ;;
	esac
done
rm -f .changes.bak
git add -A
../.docommit "$rev"
